### ISSUE TITLE
Only dragging the topmost tab bars should drag the whole window

### ISSUE THREAD

**Issue by fabiospampinato** [lehni/vscode-titlebar-less-macos#13]
Currently all tab bars can be dragged on in order to move the entire window, but I think only the top-most tab bars should behave like that. It feels weird that I can drag the whole window from its center, and this way I can't move any editors groups around.

<img width="1440" alt="screen shot 2018-08-12 at 17 04 27" src="https://user-images.githubusercontent.com/1812093/44003384-fb7cde42-9e51-11e8-8b44-066c99091da7.png">

**Comment by lehni** [comment]
Agreed. I never use the feature myself, but will look into it.

**Comment by lehni** [comment]
I've looked into this, but it's very tricky address for the various scenarios in CSS, as the configuration of split views can be very flexible... I'm not sure I can fix this. But perhaps you'd like to help out here?

**Comment by fabiospampinato** [comment]
I don't think it's possible to match them with CSS alone, the following abomination seems to work well enough, even with complicated layouts, but someone might want to nest editors even deeper and it won't work perfectly.

```css
.grid-view-container > .monaco-grid-view > .monaco-grid-branch-node > .horizontal > .split-view-container > .split-view-view > .monaco-grid-branch-node > .horizontal > .split-view-container > .split-view-view .title.tabs,
.grid-view-container > .monaco-grid-view > .monaco-grid-branch-node > .horizontal > .split-view-container > .split-view-view > .monaco-grid-branch-node > .vertical > .split-view-container > .split-view-view:first-child .title.tabs,
.grid-view-container > .monaco-grid-view > .monaco-grid-branch-node > .horizontal > .split-view-container > .split-view-view > .editor-group-container .title.tabs,
.grid-view-container > .monaco-grid-view > .monaco-grid-branch-node > .vertical > .split-view-container > .split-view-view:first-child > .monaco-grid-branch-node > .horizontal > .split-view-container > .split-view-view .title.tabs,
.grid-view-container > .monaco-grid-view > .monaco-grid-branch-node > .vertical > .split-view-container > .split-view-view:first-child > .monaco-grid-branch-node > .vertical > .split-view-container > .split-view-view:first-child .title.tabs,
.grid-view-container > .monaco-grid-view > .monaco-grid-branch-node > .vertical > .split-view-container > .split-view-view:first-child > .editor-group-container .title.tabs {
  background-color: red !important;
}
```

It matches the following layouts properly:

<img width="1440" alt="screen shot 2018-08-30 at 17 16 25" src="https://user-images.githubusercontent.com/1812093/44861671-4bf27000-ac79-11e8-82be-2e714983f215.png">
<img width="1440" alt="screen shot 2018-08-30 at 17 16 27" src="https://user-images.githubusercontent.com/1812093/44861672-4bf27000-ac79-11e8-9b58-5c096ff766d7.png">
<img width="1440" alt="screen shot 2018-08-30 at 17 16 31" src="https://user-images.githubusercontent.com/1812093/44861673-4bf27000-ac79-11e8-96f6-707ace0663b7.png">
<img width="1440" alt="screen shot 2018-08-30 at 17 16 42" src="https://user-images.githubusercontent.com/1812093/44861674-4bf27000-ac79-11e8-882a-3b4d68718ecd.png">
<img width="1440" alt="screen shot 2018-08-30 at 17 16 56" src="https://user-images.githubusercontent.com/1812093/44861675-4bf27000-ac79-11e8-9265-2b3a6c52ac5d.png">

But fails with this one (spit order matters, you can reproduce this if you split vertically first, then horizontally and then vertically again):

<img width="1440" alt="screen shot 2018-08-30 at 17 17 39" src="https://user-images.githubusercontent.com/1812093/44861717-63c9f400-ac79-11e8-98dc-5b9b60d12e67.png">

Can't you modify the CSS dynamically? With this bit of JS one could select the tab bars properly:

```js
Array.from ( document.querySelectorAll ( '.title.tabs' ) ).filter ( ele => !ele.getBoundingClientRect ().top )
```
